
-- MySQL Script generated by MySQL Workbench
-- Thu May 30 21:35:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pruebas
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pruebas` ;

-- -----------------------------------------------------
-- Schema pruebas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pruebas` DEFAULT CHARACTER SET utf8 ;
USE `pruebas` ;

-- -----------------------------------------------------
-- Table `pruebas`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebas`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `pruebas`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebas`.`tarjetas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebas`.`tarjetas` ;

CREATE TABLE IF NOT EXISTS `pruebas`.`tarjetas` (
  `id_tarjeta` INT NOT NULL AUTO_INCREMENT,
  `numero_tarjeta` VARCHAR(45) NOT NULL,
  `fecha_vencimiento` DATE NOT NULL,
  `cvv` INT NOT NULL,
  `bloqueada` TINYINT NOT NULL DEFAULT 0,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_tarjeta`),
  INDEX `fk_tarjetas_usuarios_idx` (`id_usuario` ASC) ,
  CONSTRAINT `fk_tarjetas_usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `pruebas`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebas`.`tipo_transaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebas`.`tipo_transaccion` ;

CREATE TABLE IF NOT EXISTS `pruebas`.`tipo_transaccion` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pruebas`.`transacciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pruebas`.`transacciones` ;

CREATE TABLE IF NOT EXISTS `pruebas`.`transacciones` (
  `id_transaccion` INT NOT NULL AUTO_INCREMENT,
  `monto` INT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `descripcion` VARCHAR(45) NOT NULL,
  `id_tipo` INT NOT NULL,
  `id_tarjeta` INT NOT NULL,
  PRIMARY KEY (`id_transaccion`),
  INDEX `fk_transacciones_tipo_transaccion1_idx` (`id_transaccion` ASC) ,
  INDEX `fk_transacciones_tarjetas1_idx` (`id_tarjeta` ASC) ,
  CONSTRAINT `fk_transacciones_tipo_transaccion1`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `pruebas`.`tipo_transaccion` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transacciones_tarjetas1`
    FOREIGN KEY (`id_tarjeta`)
    REFERENCES `pruebas`.`tarjetas` (`id_tarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
